name: fform
description: FForm is a dart package to build forms with a lot of fields and validations.
version: 4.1.0
homepage: https://github.com/AlexHCJP/fform

environment:
  sdk: ^3.5.3


dev_dependencies:
  lints: ^5.0.0

#flutter: