name: fform
description: FForm is a Flutter package to build forms with a lot of fields and validations.
version: 2.0.5
homepage: https://github.com/AlexHCJP/fform

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
