name: fform
description: FForm is a dart package to build forms with a lot of fields and validations.
version: 5.0.3

homepage: https://github.com/AlexHCJP/fform

repository: https://github.com/AlexHCJP/fform

issue_tracker: https://github.com/AlexHCJP/fform/issues

topics:
  - form
  - validation
  - fields

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


#flutter: