name: fform
description: FForm is a dart package to build forms with a lot of fields and validations.
version: 5.2.5

homepage: https://www.contributors.info/docs/FForm/getting-started

repository: https://github.com/AlexHCJP/fform

issue_tracker: https://github.com/AlexHCJP/fform/issues

topics:
  - form
  - validation
  - fields

funding:
  - https://www.patreon.com/c/Contributors

screenshots:
  - description: 'FForm Logo flutter package'
    path: screenshots/logo-fform.png
  - description: 'Frame FForm package for flutter forms'
    path: screenshots/big-frame.png



platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


#flutter: